services:
  oracle-db:
    build:
      context: ./oracle-db
      dockerfile: Dockerfile
    container_name: oracle-db
    ports:
      - "8080:8080"
      - "1521:1521"
    environment:
      ORACLE_HOME: /app/oracle/product/11.2.0/xe
      ORACLE_SID: ORCL
      ORACLE_USER: rm551600
      ORACLE_PASSWORD: 030900
    volumes:
      - oracledata:/app/oracle/oracledata

  dotnet-app:
    build:
      context: ./dotnet-app
      dockerfile: Dockerfile
    container_name: dotnet-app
    ports:
      - "80:80"
    depends_on:
      - oracle-db
    environment:
      ConnectionStrings__DefaultConnection: "Data Source=oracle.fiap.com.br:1521/orcl;User ID=rm551600;Password=030900;"

volumes:
  oracledata:
